apiVersion: v1
kind: Service
metadata:
  name: icondo-backend
  namespace: icondo
  labels:
    app: icondo
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: icondo
    tier: backend
